apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: my-telerik-app
spec:
  replicas: 2
  selector:
    app: my-telerik-app
  template:
    metadata:
      labels:
        app: my-telerik-app
    spec:
      containers:
        - name: telerik-app
          image: image-registry.openshift-image-registry.svc:5000/myproject/my-telerik-app:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 250m
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
      restartPolicy: Always
